FROM node:16.19-alpine3.16

RUN mkdir app
WORKDIR /app

ARG NODE_ENV
ARG DB_HOST_DATABASE_PRODUCTION
ARG DB_PORT
ARG DB_USER_PRODUCTION
ARG DB_PASSWORD_PRODUCTION
ARG DB_NAME_PRODUCTION
ARG PORT
ARG JWT_SECRET_KEY
ARG CORS_DOMAIN_ALLOW

ENV NODE_ENV=production
ENV DB_HOST_DATABASE_PRODUCTION=postgresql-backend
ENV DB_PORT=5432
ENV DB_USER_PRODUCTION=postgres
ENV DB_PASSWORD_PRODUCTION=root
ENV DB_NAME_PRODUCTION=todo-list
ENV PORT=8002
ENV JWT_SECRET_KEY=skafjklasfklsasdajf
ENV CORS_DOMAIN_ALLOW=["http://localhost:3000"]

COPY . .
RUN yarn
RUN yarn run tsc
RUN yarn run sequelize-cli db:migrate
CMD yarn run start
EXPOSE 8002/tcp

