FROM node:lts-alpine
COPY . .
ARG DB_HOST_DATABASE
ARG DB_PORT
ARG DB_USER
ARG DB_NAME
ARG DB_PASSWORD
RUN chmod 755 docker/entrypoint.sh
RUN echo "Database Host:$DB_HOST_DATABASE" && \
    yarn
EXPOSE 8050
CMD ["yarn", "start"]

